In [69]:
from pathlib import Path
import pandas as pd

project_root = Path.cwd()

if project_root.name == "notebooks":
    project_root = project_root.parent

raw_file = project_root / "data" / "raw" / "clinvar_download_20260712_233035.tsv"

df = pd.read_csv(raw_file, sep="\t")
df.head()

,Variation,Genes,Type,Condition,Classification,Review status,Molecular consequence,Protein change,Germline date last evaluated,Somatic clinical impact date last evaluated,Oncogenicity date last evaluated,GRCh37 Location,GRCh38 Location,Variation ID,VCV accession,rs_ID
0,GRCh38/hg38 11q14.3-22.3(chr11:91086659-109595...,BIRC3|C11orf54|C11orf65|C11orf87|C11orf97|CARD...,copy number loss,See cases,G: Pathogenic,no assertion criteria provided,NaN,NaN,2012/01/03,NaN,NaN,11:90819827,11:91086659,148976,VCV000148976,rs158727
1,GRCh38/hg38 11q22.1-25(chr11:100348599-1350402...,LOC124625831|LOC124625832|LOC124625833|LOC1246...,copy number gain,See cases,G: Pathogenic,"criteria provided, single submitter",NaN,NaN,2011/08/12,NaN,NaN,11:100219331,11:100348599,59772,VCV000059772,rs74367
2,NC_000011.10:g.108151767_108183227del,ATM|LOC128772354|LOC130006698|NPAT,Deletion,Ataxia-telangiectasia syndrome,G: Pathogenic,no assertion criteria provided,NaN,NaN,2019/11/20,NaN,NaN,NaN,11:108151766,694625,VCV000694625,rs682728
3,NC_000011.10:g.(?_108158326)_(108160428_?)del,NPAT|ATM,Deletion,Familial cancer of breast,G: Likely pathogenic,"criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,11:108158326,4849834,VCV004849834,rs4958086
4,NC_000011.10:g.(?_108172374)_(108178711_?)del,ATM|LOC128772354|LOC130006698|NPAT,Deletion,Familial cancer of breast,G: Pathogenic,"criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,11:108172374,4849845,VCV004849845,rs4958097

In [70]:
df.shape

(19651, 16)

In [71]:
df.columns.tolist()

['Variation',
 'Genes',
 'Type',
 'Condition',
 'Classification',
 'Review status',
 'Molecular consequence',
 'Protein change',
 'Germline date last evaluated',
 'Somatic clinical impact date last evaluated',
 'Oncogenicity date last evaluated',
 'GRCh37 Location',
 'GRCh38 Location',
 'Variation ID',
 'VCV accession',
 'rs_ID']

In [72]:
atm_missense_vus = df[
    (df["Genes"] == "ATM") &
    (df["Classification"] == "G: Uncertain significance") &
    (df["Molecular consequence"] == "missense variant")
].copy()

atm_missense_vus.shape

(4564, 16)

In [73]:
atm_missense_vus = atm_missense_vus.reset_index(drop=True)

atm_missense_vus.head(10)

,Variation,Genes,Type,Condition,Classification,Review status,Molecular consequence,Protein change,Germline date last evaluated,Somatic clinical impact date last evaluated,Oncogenicity date last evaluated,GRCh37 Location,GRCh38 Location,Variation ID,VCV accession,rs_ID
0,NM_000051.4(ATM):c.4A>C (p.Ser2Arg),ATM,single nucleotide variant,Hereditary cancer-predisposing syndrome,G: Uncertain significance,"criteria provided, single submitter",missense variant,S2R,2025/08/26,NaN,NaN,11:108098355,11:108227628,4170131,VCV004170131,rs4279232
1,NM_000051.4(ATM):c.4A>G (p.Ser2Gly),ATM,single nucleotide variant,"Hereditary cancer-predisposing syndrome, Famil...",G: Uncertain significance,"criteria provided, multiple submitters, no con...",missense variant,S2G,2024/02/19,NaN,NaN,11:108098355,11:108227628,640846,VCV000640846,rs639367
2,NM_000051.4(ATM):c.5G>C (p.Ser2Thr),ATM,single nucleotide variant,not specified,G: Uncertain significance,"criteria provided, single submitter",missense variant,S2T,2014/06/23,NaN,NaN,11:108098356,11:108227629,181943,VCV000181943,rs180377
3,NM_000051.4(ATM):c.6T>G (p.Ser2Arg),ATM,single nucleotide variant,not specified,G: Uncertain significance,"criteria provided, single submitter",missense variant,S2R,2019/12/09,NaN,NaN,11:108098357,11:108227630,1337452,VCV001337452,rs1328461
4,NM_000051.4(ATM):c.6T>A (p.Ser2Arg),ATM,single nucleotide variant,"Hereditary cancer-predisposing syndrome, Ataxi...",G: Uncertain significance,"criteria provided, multiple submitters, no con...",missense variant,S2R,2025/11/01,NaN,NaN,11:108098357,11:108227630,922075,VCV000922075,rs911284
5,NM_000051.4(ATM):c.8T>C (p.Leu3Pro),ATM,single nucleotide variant,"Hereditary cancer-predisposing syndrome, Ataxi...",G: Uncertain significance,"criteria provided, multiple submitters, no con...",missense variant,L3P,2023/01/28,NaN,NaN,11:108098359,11:108227632,453759,VCV000453759,rs460775
6,NM_000051.4(ATM):c.10G>T (p.Val4Leu),ATM,single nucleotide variant,"Hereditary cancer-predisposing syndrome, Ataxi...",G: Uncertain significance,"criteria provided, multiple submitters, no con...",missense variant,V4L,2025/01/12,NaN,NaN,11:108098361,11:108227634,481224,VCV000481224,rs475312
7,NM_000051.4(ATM):c.13C>T (p.Leu5Phe),ATM,single nucleotide variant,Ataxia-telangiectasia syndrome,G: Uncertain significance,"criteria provided, single submitter",missense variant,L5F,2022/03/10,NaN,NaN,11:108098364,11:108227637,2108203,VCV002108203,rs2159617
8,NM_000051.4(ATM):c.13C>G (p.Leu5Val),ATM,single nucleotide variant,"Hereditary cancer-predisposing syndrome, not p...",G: Uncertain significance,"criteria provided, multiple submitters, no con...",missense variant,L5V,2025/04/29,NaN,NaN,11:108098364,11:108227637,1059654,VCV001059654,rs1046907
9,NM_000051.4(ATM):c.14T>G (p.Leu5Arg),ATM,single nucleotide variant,"Hereditary cancer-predisposing syndrome, not s...",G: Uncertain significance,"criteria provided, multiple submitters, no con...",missense variant,L5R,2023/04/26,NaN,NaN,11:108098365,11:108227638,1773992,VCV001773992,rs1827098

In [74]:
print("Rows and columns:", atm_missense_vus.shape)

assert (atm_missense_vus["Genes"] == "ATM").all()
assert (atm_missense_vus["Classification"] == "G: Uncertain significance").all()
assert (atm_missense_vus["Molecular consequence"] == "missense variant").all()

print("All rows passed the filters!")

Rows and columns: (4564, 16)
All rows passed the filters!

In [75]:
processed_folder = project_root / "data" / "processed" 
processed_folder.mkdir(parents=True, exist_ok=True) 

output_file = processed_folder / "atm_missense_vus_all.csv" #in processed_folder path in this csv

atm_missense_vus.to_csv(output_file, index=False)

print("Saved to:", output_file)

Saved to: c:\Users\Dell - i5 11th Gen\Desktop\clinvar-gnomad-vus-analyzer\data\processed\atm_missense_vus_all.csv

In [76]:
# check eligible variants bases
eligible_variants = atm_missense_vus[
    (
        atm_missense_vus["rs_ID"]
        .astype("string")
        .str.fullmatch(r"rs\d+", na=False)
    )
    &
    (atm_missense_vus["GRCh38 Location"].notna())
    &
    (
        atm_missense_vus["Review status"]
        .str.startswith("criteria provided", na=False)
    )
].copy()

In [ ]:
# save candidates to processed

candidate_variants = eligible_variants.reset_index(drop=True)

# path for candidate variants
candidate_file = (
    processed_folder
    / "atm_clinvar_candidates.csv"
)

candidate_variants.to_csv(
    candidate_file,
    index=False
)

print("Candidate variants:", candidate_variants.shape[0])
print("Saved to:", candidate_file)

candidate_variants[
    [
        "Variation",
        "Protein change",
        "Review status",
        "GRCh38 Location",
        "Variation ID",
        "VCV accession",
        "rs_ID"
    ]
].head(20)

Candidate variants: 4534
Saved to: c:\Users\Dell - i5 11th Gen\Desktop\clinvar-gnomad-vus-analyzer\data\processed\atm_clinvar_candidates.csv

,Variation,Protein change,Review status,GRCh38 Location,Variation ID,VCV accession,rs_ID
0,NM_000051.4(ATM):c.4A>C (p.Ser2Arg),S2R,"criteria provided, single submitter",11:108227628,4170131,VCV004170131,rs4279232
1,NM_000051.4(ATM):c.4A>G (p.Ser2Gly),S2G,"criteria provided, multiple submitters, no con...",11:108227628,640846,VCV000640846,rs639367
2,NM_000051.4(ATM):c.5G>C (p.Ser2Thr),S2T,"criteria provided, single submitter",11:108227629,181943,VCV000181943,rs180377
3,NM_000051.4(ATM):c.6T>G (p.Ser2Arg),S2R,"criteria provided, single submitter",11:108227630,1337452,VCV001337452,rs1328461
4,NM_000051.4(ATM):c.6T>A (p.Ser2Arg),S2R,"criteria provided, multiple submitters, no con...",11:108227630,922075,VCV000922075,rs911284
5,NM_000051.4(ATM):c.8T>C (p.Leu3Pro),L3P,"criteria provided, multiple submitters, no con...",11:108227632,453759,VCV000453759,rs460775
6,NM_000051.4(ATM):c.10G>T (p.Val4Leu),V4L,"criteria provided, multiple submitters, no con...",11:108227634,481224,VCV000481224,rs475312
7,NM_000051.4(ATM):c.13C>T (p.Leu5Phe),L5F,"criteria provided, single submitter",11:108227637,2108203,VCV002108203,rs2159617
8,NM_000051.4(ATM):c.13C>G (p.Leu5Val),L5V,"criteria provided, multiple submitters, no con...",11:108227637,1059654,VCV001059654,rs1046907
9,NM_000051.4(ATM):c.14T>G (p.Leu5Arg),L5R,"criteria provided, multiple submitters, no con...",11:108227638,1773992,VCV001773992,rs1827098
10,NM_000051.4(ATM):c.19G>T (p.Asp7Tyr),D7Y,"criteria provided, single submitter",11:108227643,2743808,VCV002743808,rs2907161
11,NM_000051.4(ATM):c.19G>C (p.Asp7His),D7H,"criteria provided, multiple submitters, no con...",11:108227643,1014478,VCV001014478,rs1009361
12,NM_000051.4(ATM):c.23T>C (p.Leu8Pro),L8P,"criteria provided, multiple submitters, no con...",11:108227647,641026,VCV000641026,rs639368
13,NM_000051.4(ATM):c.25C>T (p.Leu9Phe),L9F,"criteria provided, multiple submitters, no con...",11:108227649,1000339,VCV001000339,rs994169
14,NM_000051.4(ATM):c.28A>C (p.Ile10Leu),I10L,"criteria provided, single submitter",11:108227652,4800505,VCV004800505,rs4909087
15,NM_000051.4(ATM):c.28A>G (p.Ile10Val),I10V,"criteria provided, multiple submitters, no con...",11:108227652,233834,VCV000233834,rs233884
16,NM_000051.4(ATM):c.31T>C (p.Cys11Arg),C11R,"criteria provided, multiple submitters, no con...",11:108227655,1728802,VCV001728802,rs1788437
17,NM_000051.4(ATM):c.32G>A (p.Cys11Tyr),C11Y,"criteria provided, single submitter",11:108227656,3232960,VCV003232960,rs3389296
18,NM_000051.4(ATM):c.32G>C (p.Cys11Ser),C11S,"criteria provided, multiple submitters, no con...",11:108227656,1729959,VCV001729959,rs1792166
19,NM_000051.4(ATM):c.34T>C (p.Cys12Arg),C12R,"criteria provided, single submitter",11:108227658,407554,VCV000407554,rs397766