In [1]:
from pathlib import Path
import pandas as pd

# set project root
project_root = Path.cwd()

if project_root.name == "notebooks":
    project_root = project_root.parent

project_root

WindowsPath('c:/Users/Dell - i5 11th Gen/Desktop/clinvar-gnomad-vus-analyzer')

In [4]:
# get tsv
tsv = (
    project_root 
    / "data"
    / "raw"
    / "clinvar_download_20260712_233035.tsv"
)
df = pd.read_csv(tsv, sep="\t")
df.head()

,Variation,Genes,Type,Condition,Classification,Review status,Molecular consequence,Protein change,Germline date last evaluated,Somatic clinical impact date last evaluated,Oncogenicity date last evaluated,GRCh37 Location,GRCh38 Location,Variation ID,VCV accession,rs_ID
0,GRCh38/hg38 11q14.3-22.3(chr11:91086659-109595...,BIRC3|C11orf54|C11orf65|C11orf87|C11orf97|CARD...,copy number loss,See cases,G: Pathogenic,no assertion criteria provided,NaN,NaN,2012/01/03,NaN,NaN,11:90819827,11:91086659,148976,VCV000148976,rs158727
1,GRCh38/hg38 11q22.1-25(chr11:100348599-1350402...,LOC124625831|LOC124625832|LOC124625833|LOC1246...,copy number gain,See cases,G: Pathogenic,"criteria provided, single submitter",NaN,NaN,2011/08/12,NaN,NaN,11:100219331,11:100348599,59772,VCV000059772,rs74367
2,NC_000011.10:g.108151767_108183227del,ATM|LOC128772354|LOC130006698|NPAT,Deletion,Ataxia-telangiectasia syndrome,G: Pathogenic,no assertion criteria provided,NaN,NaN,2019/11/20,NaN,NaN,NaN,11:108151766,694625,VCV000694625,rs682728
3,NC_000011.10:g.(?_108158326)_(108160428_?)del,NPAT|ATM,Deletion,Familial cancer of breast,G: Likely pathogenic,"criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,11:108158326,4849834,VCV004849834,rs4958086
4,NC_000011.10:g.(?_108172374)_(108178711_?)del,ATM|LOC128772354|LOC130006698|NPAT,Deletion,Familial cancer of breast,G: Pathogenic,"criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,11:108172374,4849845,VCV004849845,rs4958097

In [6]:
# filter candidates for VUS missense
candidate_variants = df[
    (df["Genes"] == "ATM") &
    (df["Genes"] == "ATM") &
    (df["Classification"] == "G: Uncertain significance") &
    (df["Molecular consequence"] == "missense variant") &
    (
        df["rs_ID"]
        .astype("string")
        .str.fullmatch(r"rs\d+", na=False)
    )
    &
    (df["GRCh38 Location"].notna())
    &
    (
        df["Review status"]
        .str.startswith("criteria provided", na=False)
    )
    ].copy().reset_index(drop=True)

candidate_variants.head()

,Variation,Genes,Type,Condition,Classification,Review status,Molecular consequence,Protein change,Germline date last evaluated,Somatic clinical impact date last evaluated,Oncogenicity date last evaluated,GRCh37 Location,GRCh38 Location,Variation ID,VCV accession,rs_ID
0,NM_000051.4(ATM):c.4A>C (p.Ser2Arg),ATM,single nucleotide variant,Hereditary cancer-predisposing syndrome,G: Uncertain significance,"criteria provided, single submitter",missense variant,S2R,2025/08/26,NaN,NaN,11:108098355,11:108227628,4170131,VCV004170131,rs4279232
1,NM_000051.4(ATM):c.4A>G (p.Ser2Gly),ATM,single nucleotide variant,"Hereditary cancer-predisposing syndrome, Famil...",G: Uncertain significance,"criteria provided, multiple submitters, no con...",missense variant,S2G,2024/02/19,NaN,NaN,11:108098355,11:108227628,640846,VCV000640846,rs639367
2,NM_000051.4(ATM):c.5G>C (p.Ser2Thr),ATM,single nucleotide variant,not specified,G: Uncertain significance,"criteria provided, single submitter",missense variant,S2T,2014/06/23,NaN,NaN,11:108098356,11:108227629,181943,VCV000181943,rs180377
3,NM_000051.4(ATM):c.6T>G (p.Ser2Arg),ATM,single nucleotide variant,not specified,G: Uncertain significance,"criteria provided, single submitter",missense variant,S2R,2019/12/09,NaN,NaN,11:108098357,11:108227630,1337452,VCV001337452,rs1328461
4,NM_000051.4(ATM):c.6T>A (p.Ser2Arg),ATM,single nucleotide variant,"Hereditary cancer-predisposing syndrome, Ataxi...",G: Uncertain significance,"criteria provided, multiple submitters, no con...",missense variant,S2R,2025/11/01,NaN,NaN,11:108098357,11:108227630,922075,VCV000922075,rs911284

In [ ]:
# output candidates
output_path = (
    project_root
    / "data"
    / "processed"
    / "atm_clinvar_candidates.csv"
)

candidate_variants.to_csv(output_path, index=False)
print("candidate_variants saved to: ", output_path)

candidate_variants saved to:  c:\Users\Dell - i5 11th Gen\Desktop\clinvar-gnomad-vus-analyzer\data\processed\atm_clinvar_candidates.csv